# Ejercicios de Numpy
Aprendizaje de Maquina I - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [2]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [3]:
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)

[1 2 3 4 5]


In [4]:
lista = [1, 2, 3, 4, 5]

Ejercicio 3: Suma los siguientes dos arrays

In [5]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])



In [6]:
suma = np.add(a,b)
print(suma)

[[11 13 15]
 [17 19 21]]


Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [10]:
a = np.array([[4,2,2],
              [4,1,0]])
multiplicar = np.matmul(np.reshape(suma,(3,2)),a)
print(multiplicar)

[[ 96  35  22]
 [128  47  30]
 [160  59  38]]


Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [14]:
a = np.array([x for x in range(9)])
print(np.shape(a))
print(np.reshape(a,(3,3)))

(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [18]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])


[[2 3 1]
 [4 2 1]]


In [19]:
aInt = a.astype(int)
print(aInt)

[[2 3 1]
 [4 2 1]]


Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [20]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [34]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])


In [38]:
aConcH = np.concatenate([a1,a2],axis=1)
print(aConcH)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Ejercicio 9: Cocatena de forma vertical los mismos array

In [39]:
aConcV = np.concatenate([a1,a2],axis=0)
print(aConcV)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [65]:
a = np.arange(0,101,2)
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [69]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

In [70]:
c = np.where(a>b)
print(c)

(array([2, 4]),)


Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [71]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [72]:
np.full((2,3),23)

array([[23, 23, 23],
       [23, 23, 23]])

Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [76]:
np.random.normal(0,1,size=(8,2))

array([[ 0.99896159,  0.39651396],
       [ 0.17789113,  0.69217398],
       [ 1.40871764, -0.98106923],
       [ 2.36076226, -1.06654135],
       [ 1.87995581,  0.14550762],
       [-1.39370117,  2.81498308],
       [-1.24454397, -0.4916318 ],
       [-0.69182796, -0.00349629]])

Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [91]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

In [92]:
c = np.matmul(a,b)
print(c)    #Matrix mult
d = a*b
print(d)    #Array mult

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [96]:
sort = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

In [99]:
ind = np.argsort(sort,axis=0)
take = np.take_along_axis(sort, ind, axis=0)
print(take)

[   0    1    2    2   38   82   91  199  292  299  387  923  939 1101]


----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))